### PR TITLE
fix: not disabling save button while adding user

### LINKED ISSUE #63: Adding user shows no loading indicator nor disables button

### PR DESCRIPTION
**Pull request by vieiralucas**
Closes #63

### CODE REVIEW

**Review by lucasfcosta — APPROVED** [review]
LGTM

File: apps/web/src/components/forms/user.tsx [hunk 1]
```diff
@@ -22,13 +23,17 @@ export default function UserForm({ workspaceId, onSubmit }: UserFormProps) {
   const { register, formState, handleSubmit } = useForm<UserFormValues>({
     mode: 'onChange',
   })
+  const [loading, setLoading] = useState(false)
```
Comment (vtfg) [inline apps/web/src/components/forms/user.tsx:26]: `react-hook-form` has an [`isSubmitting`](https://react-hook-form.com/docs/useform/formstate#:~:text=any%20runtime%20error.-,isSubmitting,-boolean) boolean inside `formState`, which is true while the `handleSubmit` promise is resolving.

I quick tested and it does work with `useCallback`, so it will help you save some memory by removing this state.

Comment (vieiralucas) [reply apps/web/src/components/forms/user.tsx:26]: Loved it, you're the best! I'll use it.
