### PR TITLE
fix multi-y-axis naming

### LINKED ISSUE #121: fix naming Y axis when there are multiple series

### PR DESCRIPTION
**Pull request by lucasfcosta**
Closes #121

### CODE REVIEW

File: apps/web/src/components/v2Editor/customBlocks/python/index.tsx [hunk 1]
```diff
@@ -525,7 +525,7 @@ function PythonBlock(props: Props) {
 
       <div
         className={clsx(
-          'absolute h-full transition-opacity opacity-0 group-hover/block:opacity-100 pl-1.5 right-0 top-0 translate-x-full flex flex-col gap-y-1',
+          'absolute h-full transition-opacity opacity-0 group-hover/block:opacity-100 pl-1.5 right-0 top-0 translate-x-full flex flex-col gap-y-1 z-20',
```
Comment (lucasfcosta) [inline apps/web/src/components/v2Editor/customBlocks/python/index.tsx:528]: not related, but the tooltip for this button was covered by the small "PNG" button at the bottom of the visualization block

File: apps/web/src/components/v2Editor/customBlocks/visualization/VisualizationControls.tsx [hunk 2]
```diff
@@ -340,6 +323,31 @@ function VisualizationControls(props: Props) {
...
 
+  const axisNameComponents = props.yAxes.map((yAxis, yI) =>
+    yAxis.series.map((_, sI) => {
+      return (
+        <div>
+          <label
+            htmlFor={`rightYAxisName-${yI}-${sI}`}
+            className="block text-xs font-medium leading-6 text-gray-900 pb-1"
+          >
+            {yI === 0 && sI === 0 ? 'Left' : 'Right'} Y-Axis Name
```
Comment (lucasfcosta) [inline apps/web/src/components/v2Editor/customBlocks/visualization/VisualizationControls.tsx:334]: All axes names except the very first one will be on the right.
